# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:

  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world
  vmImage: 'ubuntu-latest'

steps:
- task: katalonTask@0
  inputs:
    version: '7.6.1'
    executeArgs: '-browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/Regression Tests/All tests"'

